services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: api-gateway
    environment:
      - SERVICE_NAME=api-gateway
      - SERVICE_PORT=50051
    ports:
      - "50051:50051"
    networks:
      - dubpay-network
    depends_on:
      - fraud-detection-service
      - notification-service
      - social-service
      - transaction-service
      - user-service
      - wallet-service

  fraud-detection-service:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: fraud-detection-service
    environment:
      - SERVICE_NAME=fraud-detection-service
      - SERVICE_PORT=50051
    ports:
      - "50052:50051"
    networks:
      - dubpay-network

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: notification-service
    environment:
      - SERVICE_NAME=notification-service
      - SERVICE_PORT=50051
    ports:
      - "50053:50051"
    networks:
      - dubpay-network

  social-service:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: social-service
    environment:
      - SERVICE_NAME=social-service
      - SERVICE_PORT=50051
    ports:
      - "50054:50051"
    networks:
      - dubpay-network
    depends_on:
      - user-service

  transaction-service:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: transaction-service
    environment:
      - SERVICE_NAME=transaction-service
      - SERVICE_PORT=50051
    ports:
      - "50055:50051"
    networks:
      - dubpay-network
    depends_on:
      - wallet-service
      - fraud-detection-service
      - notification-service

  user-service:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: user-service
    environment:
      - SERVICE_NAME=user-service
      - SERVICE_PORT=50051
    ports:
      - "50056:50051"
    networks:
      - dubpay-network

  wallet-service:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: wallet-service
    environment:
      - SERVICE_NAME=wallet-service
      - SERVICE_PORT=50051
    ports:
      - "50057:50051"
    networks:
      - dubpay-network
    depends_on:
      - user-service

networks:
  dubpay-network:
    driver: bridge
