[package]
name = "api-gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
tonic.workspace = true
prost.workspace = true
prost-types.workspace = true
axum.workspace = true
serde.workspace = true

[build-dependencies]
build-common = { path = "../../build-common" }
