[package]
name = "build-common"
version = "0.1.0"
edition = "2021"

[lib]
name = "build_common"
path = "src/lib.rs"

[dependencies]
tonic-build.workspace = true
tokio.workspace = true
tonic.workspace = true
prost.workspace = true
prost-types.workspace = true
